"""
Engineering Workflow Orchestrator — Phase 9

Human-in-the-loop pipeline engine: analyze → create → install → code →
test → debug → approval → launch across isolated sandboxes (temp → test → live).

Wraps: SandboxManager, ApprovalGate, DebugLoop, TaskOrchestrator,
RollbackManager, EventBus, ServiceManager.
"""

from dataclasses import dataclass, field
from enum import Enum
import time
from typing import Any, Dict, List, Optional

from core.event_bus import EventBus
from core.service_manager import ServiceManager
from core_runtime.task_orchestration import TaskOrchestrator
from core_runtime.sandbox_manager import SandboxManager
from core_runtime.approval_gate import ApprovalGate
from core_runtime.debug_loop import DebugLoop


class PipelineStage(Enum):
    ANALYZE = "analyze"
    CREATE = "create"
    INSTALL = "install"
    CODE = "code"
    TEST = "test"
    DEBUG = "debug"
    APPROVAL = "approval"
    LAUNCH = "launch"


@dataclass
class WorkflowSpec:
    intent: str
    file_changes: List[Dict[str, str]] = field(default_factory=list)
    dependencies: List[str] = field(default_factory=list)
    plan: Dict[str, Any] = field(default_factory=dict)
    status: str = "pending"


@dataclass
class PipelineResult:
    status: str
    sandbox_id: Optional[str] = None
    stage: Optional[PipelineStage] = None
    spec: Optional[WorkflowSpec] = None
    error: Optional[str] = None
    debug_exhausted: bool = False


class EngineeringWorkflowOrchestrator:
    _service_name = "engineering_workflow_orchestrator"

    def __init__(
        self,
        sandbox_manager: SandboxManager = None,
        approval_gate: ApprovalGate = None,
        debug_loop: DebugLoop = None,
        task_orchestrator: TaskOrchestrator = None,
        rollback_manager=None,
        event_bus: EventBus = None,
        service_manager: ServiceManager = None,
        logger=None,
    ):
        self._sandbox_manager = sandbox_manager or SandboxManager(logger=logger)
        self._approval_gate = approval_gate or ApprovalGate(logger=logger)
        self._debug_loop = debug_loop or DebugLoop(logger=logger)
        self._task_orchestrator = task_orchestrator or TaskOrchestrator()
        from safety.rollback_manager import RollbackManager
        self._rollback_manager = rollback_manager or RollbackManager(logger=logger)
        self._event_bus = event_bus or EventBus()
        self._service_manager = service_manager
        self._logger = logger
        self._log = logger.info if logger else lambda m: None
        self._current_sandbox_id: Optional[str] = None
        self._current_spec: Optional[WorkflowSpec] = None

    def start(self):
        self._log("EngineeringWorkflowOrchestrator started")

    def stop(self):
        if self._current_sandbox_id:
            self._sandbox_manager.destroy_sandbox(self._current_sandbox_id)
        self._log("EngineeringWorkflowOrchestrator stopped")

    def analyze(self, user_intent: str) -> WorkflowSpec:
        self._log(f"Analyzing intent: {user_intent}")
        spec = WorkflowSpec(
            intent=user_intent,
            file_changes=[
                {"file": f"src/{user_intent[:20].replace(' ', '_')}.py", "type": "create"}
            ],
            dependencies=["pytest"],
            plan={"steps": ["create file", "run tests"]},
            status="analyzed",
        )
        return spec

    def create(self, spec: WorkflowSpec) -> WorkflowSpec:
        self._log("Creating implementation plan")
        spec.plan = {
            "steps": [
                {"name": "create_file", "handler": lambda ctx: ctx.get("file")},
                {"name": "run_tests", "handler": lambda ctx: True},
            ]
        }
        return spec

    def install(self, spec: WorkflowSpec, sandbox_id: str) -> bool:
        self._log(f"Installing dependencies in sandbox {sandbox_id}")
        sandbox = self._sandbox_manager.get_sandbox(sandbox_id)
        if not sandbox:
            return False
        for dep in spec.dependencies:
            self._log(f"  Installing {dep}")
        return True

    def code(self, spec: WorkflowSpec, sandbox_id: str) -> bool:
        self._log(f"Coding in sandbox {sandbox_id}")
        sandbox = self._sandbox_manager.get_sandbox(sandbox_id)
        if not sandbox:
            return False
        import os
        for fc in spec.file_changes:
            path = f"{sandbox.worktree_path}/{fc['file']}"
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w") as f:
                f.write(f"# Auto-generated by EWO for: {spec.intent}\n")
        return True

    def test(self, spec: WorkflowSpec, sandbox_id: str) -> bool:
        self._log(f"Running tests in sandbox {sandbox_id}")
        sandbox = self._sandbox_manager.get_sandbox(sandbox_id)
        if not sandbox:
            return False
        import subprocess
        try:
            result = subprocess.run(
                ["python", "-m", "pytest", sandbox.worktree_path, "-v"],
                capture_output=True, text=True, timeout=300
            )
            passed = result.returncode == 0
            self._log(f"Tests {'passed' if passed else 'failed'} in sandbox {sandbox_id}")
            if not passed:
                self._log(f"Test output: {result.stdout[:500]}")
            return passed
        except Exception as e:
            self._log(f"Test run failed for sandbox {sandbox_id}: {e}")
            return False
        finally:
            self._event_bus.publish("workflow.stage.completed", {
                "stage": PipelineStage.TEST.value,
                "sandbox_id": sandbox_id,
            })

    def _execute_debug(self, sandbox_id: str, spec: WorkflowSpec) -> Dict[str, Any]:
        def fix_handler():
            return self.test(spec, sandbox_id)

        result = self._debug_loop.auto_fix(sandbox_id, fix_handler)
        return result

    def _execute_approval(self, sandbox_id: str, from_env: str, to_env: str) -> bool:
        changes = [
            {"file": fc["file"], "type": fc.get("type", "create")}
            for fc in self._current_spec.file_changes
        ]
        risk = self._approval_gate.score_promotion(changes, sandbox_path=sandbox_id)
        result = self._approval_gate.request_promotion_approval(
            sandbox_id, from_env, to_env, risk
        )
        if result.get("auto_approved"):
            self._log(f"Promotion {sandbox_id} {from_env}→{to_env} auto-approved")
            return True
        deadline = time.time() + self._approval_gate.PROMOTION_TIMEOUT_SECONDS
        while time.time() < deadline:
            if self._approval_gate.is_promotion_approved(sandbox_id, from_env, to_env):
                return True
            time.sleep(1)
        self._log(f"Approval timeout for {sandbox_id} {from_env}→{to_env}")
        return False

    def _rollback(self, sandbox_id: str) -> bool:
        self._log(f"Rolling back sandbox {sandbox_id}")
        self._sandbox_manager.snapshot_sandbox(sandbox_id, "pre-rollback")
        return self._rollback_manager.rollback(sandbox_id)

    def run(self, user_intent: str) -> PipelineResult:
        self._log(f"Starting workflow: {user_intent}")
        try:
            spec = self.analyze(user_intent)
            spec = self.create(spec)

            sandbox_id = self._sandbox_manager.create_sandbox("wf-" + user_intent[:8])
            self._current_sandbox_id = sandbox_id
            self._current_spec = spec

            container_id = self._sandbox_manager.create_container(sandbox_id)
            if container_id:
                self._log(f"Container {container_id} started for sandbox {sandbox_id}")

            if not self.install(spec, sandbox_id):
                if not self._rollback(sandbox_id):
                    self._log(f"Rollback may have failed for {sandbox_id}")
                return PipelineResult(status="failed", stage=PipelineStage.INSTALL,
                                      error="install failed", sandbox_id=sandbox_id)

            if not self.code(spec, sandbox_id):
                if not self._rollback(sandbox_id):
                    self._log(f"Rollback may have failed for {sandbox_id}")
                return PipelineResult(status="failed", stage=PipelineStage.CODE,
                                      error="coding failed", sandbox_id=sandbox_id)

            if not self.test(spec, sandbox_id):
                debug_result = self._execute_debug(sandbox_id, spec)
                if debug_result.get("exhausted"):
                    return PipelineResult(
                        status="failed", stage=PipelineStage.DEBUG,
                        error="debug loop exhausted", sandbox_id=sandbox_id,
                        debug_exhausted=True
                    )

            self._event_bus.publish("workflow.stage.completed", {
                "stage": PipelineStage.APPROVAL.value,
                "sandbox_id": sandbox_id,
            })

            sandbox = self._sandbox_manager.get_sandbox(sandbox_id)

            # Two-gate promotion: temp→test, then test→live
            for from_env, to_env in [("temp", "test"), ("test", "live")]:
                if sandbox and sandbox.environment.value != from_env:
                    # Sandbox already promoted past this stage (e.g. running in test env)
                    continue
                if not self._execute_approval(sandbox_id, from_env, to_env):
                    return PipelineResult(status="failed", stage=PipelineStage.APPROVAL,
                                          error="approval denied", sandbox_id=sandbox_id)
                self._sandbox_manager.promote_environment(sandbox_id)
                self._sandbox_manager.snapshot_sandbox(sandbox_id, f"post-{to_env}-promotion")

            self._sandbox_manager.snapshot_sandbox(sandbox_id, "post-launch")

            return PipelineResult(
                status="success",
                sandbox_id=sandbox_id,
                stage=PipelineStage.LAUNCH,
                spec=spec,
            )

        except Exception as e:
            self._log(f"Workflow failed: {e}")
            if self._current_sandbox_id:
                if not self._rollback(self._current_sandbox_id):
                    self._log(f"Rollback may have failed for {self._current_sandbox_id}")
            return PipelineResult(status="failed", error=str(e))